FROM python:3.6

ENV ES_HOST elasticsearch
ENV ES_USER elastic
ENV ES_PASSWORD changeme

RUN apt-get update && apt-get upgrade -y

WORKDIR /home/reactor

ADD requirements*.txt ./
RUN pip install -r requirements-dev.txt -r requirements.txt

ADD setup.py LICENSE README.md ./
ADD reactor ./reactor/

# Install Reactor
RUN python setup.py install && \
    pip install -e .