FROM python:3.6

ENV ES_HOST elasticsearch
ENV ES_USER elastic
ENV ES_PASSWORD changeme

RUN apt-get update && apt-get upgrade -y

WORKDIR /home/reactor

COPY requirements*.txt ./
RUN pip install -r requirements-dev.txt -r requirements.txt

COPY setup.py LICENSE README.md ./
COPY reactor ./reactor
COPY tests ./tests

# Install Reactor
RUN python setup.py install && \
    pip install -e .